name: Duplicate GitHub Issue Detection

on:
  issues:
    types: [opened]

jobs:
  detect-duplicates:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Needed to comment on issues
      contents: write  # Needed to commit files

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.5.3 numpy==1.23.5 torch==1.12.1 transformers==4.24.0 sentence-transformers==2.2.2 gensim==4.3.0 scikit-learn==1.2.0 tensorflow==2.10.0 joblib==1.2.0 requests==2.28.1 beautifulsoup4==4.11.1 nltk==3.7
        continue-on-error: false

      # Download NLTK resources
      - name: Download NLTK resources
        run: |
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('wordnet'); nltk.download('punkt_tab')"
        continue-on-error: false

      # Verify model files
      - name: Verify model files
        run: |
          ls -l models/
          if [ ! -f models/best_traditional_model.h5 ]; then echo "Missing best_traditional_model.h5"; exit 1; fi
          if [ ! -f models/meta_model.joblib ]; then echo "Missing meta_model.joblib"; exit 1; fi
          if [ ! -f models/scaler.joblib ]; then echo "Missing scaler.joblib"; exit 1; fi
          if [ ! -f models/tfidf_title.joblib ]; then echo "Missing tfidf_title.joblib"; exit 1; fi
          if [ ! -f models/tfidf_body.joblib ]; then echo "Missing tfidf_body.joblib"; exit 1; fi
          if [ ! -f models/w2v_title.model ]; then echo "Missing w2v_title.model"; exit 1; fi
          if [ ! -f models/w2v_body.model ]; then echo "Missing w2v_body.model"; exit 1; fi
          if [ ! -f models/best_model_name.txt ]; then echo "Missing best_model_name.txt"; exit 1; fi
          if [ ! -d models/fine_tuned_codebert_model ]; then echo "Missing fine_tuned_codebert_model"; exit 1; fi

      # Run the duplicate detection script
      - name: Run duplicate detection
        run: |
          python detect_duplicates.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Comment on the issue with results
      - name: Comment on issue
        if: success()
        run: |
          COMMENT_BODY=$(python -c "import pandas as pd; df = pd.read_csv('duplicate_ranking.csv'); print('Top 5 potential duplicates:\n' + df.head(5)[['issue_number', 'fetched_title', 'hybrid_prob']].to_markdown(index=False))")
          ISSUE_NUMBER=${{ github.event.issue.number }}
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments \
            -d "{\"body\": \"$COMMENT_BODY\"}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the output CSV as an artifact
      - name: Upload duplicate_ranking.csv
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: duplicate_ranking
          path: duplicate_ranking.csv
